esp_toml_version = 1.0

firmware_images_url = "https://firmware-proxy.netlify.app/.netlify/functions/get-firmware"


supported_apps = ["keybot"]

[keybot]
chipsets = ["ESP32"]
image.esp32 = "keybot_merged.bin"
android_app_url = ""
ios_app_url = ""
