esp_toml_version = 1.0

firmware_images_url = "https://github.com/albal/keybot/releases/download/v0.1.1/"


supported_apps = ["keybot"]

[keybot]
chipsets = ["ESP32"]
image.esp32 = "keybot_merged.bin"
android_app_url = ""
ios_app_url = ""
